### ISSUE TITLE
How to fix the week day data?

### ISSUE THREAD

**Issue by anotherWill** [nielssp/jqCandlestick#2]
Thanks for you develop.

When I request the day line of stock.
such as Monday, TuesDay...Friday,
But Saturday and Sunday will be blank in candleStick chart.
Some way I can let the blank missing?

**Comment by nielssp** [comment]
Hi,
I'm not sure I understand the problem. Could you post a minimal code sample?

**Comment by anotherWill** [comment]
> Hi,
> I'm not sure I understand the problem. Could you post a minimal code sample?

you can test with data(stock market is not open in Saturday and  Sundany ) :
[[1594166400000,8.85,9.25,8.77,9.13,20484321],[1594252800000,9.1,9.36,9.05,9.22,17523287],[1594339200000,9.16,9.58,9.15,9.2,21386960],[1594598400000,9.18,9.46,9.14,9.41,17575627],[1594684800000,9.4,9.5,9.14,9.28,17106552],[1594771200000,9.32,9.44,9.03,9.06,17429641],[1594857600000,9.06,9.18,8.73,8.79,14521638],[1594944000000,8.81,8.89,8.69,8.83,11689578],[1595203200000,8.85,9.2,8.85,9.16,13441942],[1595289600000,9.13,9.4,9.08,9.25,15241719],[1595376000000,9.28,9.43,9.2,9.28,14262446],[1595462400000,9.22,9.26,8.9,9.16,13861138],[1595548800000,9.13,9.21,8.8,8.85,13715605],[1595808000000,8.88,8.93,8.54,8.63,14708322],[1595894400000,8.65,8.73,8.58,8.66,6450153],[1595980800000,8.63,8.8,8.48,8.78,9112573],[1596067200000,8.77,8.84,8.72,8.73,6625317],[1596153600000,8.7,8.9,8.68,8.83,8550737],[1596412800000,8.89,9.08,8.88,9.05,10955167],[1596499200000,9.06,9.29,9,9.13,15518484],[1596585600000,9.12,9.22,9.01,9.14,9694190],[1596672000000,9.18,9.22,9.04,9.13,8823978],[1596758400000,9.23,9.7,9.15,9.31,36604117],[1597017600000,9.43,10.24,9.42,9.99,44459648],[1597104000000,9.9,10.44,9.8,10.03,45672288],[1597190400000,10.18,10.42,9.85,10.12,33428015],[1597276800000,10.12,10.23,9.86,9.88,21738244],[1597363200000,9.88,10.87,9.87,10.87,53035091],[1597622400000,11.35,11.96,11.35,11.96,54918614],[1597708800000,12.83,13.16,12.83,13.16,30607324],[1597795200000,14.35,14.48,12.93,13,181506944],[1597881600000,12.7,14.3,12.65,14.3,78486711],[1597968000000,15.05,15.6,13.01,13.3,143509002],[1598227200000,14.05,14.63,14.05,14.63,31974822],[1598313600000,16.09,16.09,15.77,16.09,36099094],[1598400000000,16,17.7,15.13,16.8,173736964],[1598486400000,16.5,16.5,15.12,15.12,39495594],[1598572800000,15,15.37,13.85,14.32,110861370],[1598832000000,14.85,15.75,14.38,14.5,114557321],[1598918400000,14.5,15.08,13.69,14.41,104705175]]
